config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    resources :users
    resources :divisions
    resources :targets
    resources :teams
    resources :employees
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    scope "(:locale)", locale: /en|ar/ do
      root :to => "users#index"
    end
  

end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :team, optional: true
    has_one :division, dependent: :nullify

    # validation
    validates :email, presence: true, format: {with:/[a-z]+@.+\.\S+\z/}, uniqueness: true
    validates :name, presence: true
    validates :job, presence: true
    validates :salary, presence: true, numericality: { greater_than_or_equal_to: 10000, less_than_or_equal_to: 30000 }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
    @teams = Team.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to "/employees", notice: t("create" )}
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: t("update") }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: t("destroy") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :email, :job, :salary, :employee_status, :team_id, :division_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong><%=t "Name"%>:</strong>
    <%= employee.name %>
  </p>

  <p>
    <strong><%= t "Email"%>:</strong>
    <%= employee.email %>
  </p>

  <p>
    <strong><%= t"Job"%>:</strong>
    <%= employee.job %>
  </p>

  <p>
    <strong><%= t "Salary"%>:</strong>
    <%= employee.salary %>
  </p>



  <p>
    <strong><%= t "Employment_status"%>:</strong>
    <%= employee.employee_status %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
    <h2> <%= t 'globals.forms.messages.errors.multiple errors', count: employee.errors.count %> </h2>
      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "mb-1">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class = "mb-1">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class = "mb-3">
    <%= form.label :job, style: "display: block" %>
    <%= form.text_field :job, class: "form-control" %>
  </div>

  <div class = "mb-3">
    <%= form.label :salary, style: "display: block" %>
    <%= form.text_field :salary, class: "form-control" %>
  </div>

  <div class = "mb-3">
   
    <%= form.label :team_id, style: "display: block" %>
    <%= form.collection_select :team_id, Team.all, :id, :name, include_blank: true, class: "form-control" %>

  </div>
  
  <div class = "mb-3">
    <%= form.label :division_id, style: "display: block" %>
    <%= form.collection_select :division_id, Division.all, :id, :name, include_blank: true, class: "form-control"%>
  </div>


  <div class = "mb-1">
    <%= form.label :employee_status, style: "display: block" %>
    <%= form.text_field :employee_status, class: "form-control" %>
  </div>

  <div class = "mb-1">
    <%= form.submit t("Create Employee"), class: "btn btn-primary"%>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1><%= t "Editing"%></h1>

<%= render "form", employee: @employee %>

<br>

<div>

  <%= link_to t("Back to employees"), employees_path %>
</div>

app/views/employees/index.html.erb
<h2><%= t "Employees"%></h2>
<%= link_to t( "New employee"), new_employee_path, style: "color: black;" %>

<div id="employees">
  <table class="table">
  <thead>
    <tr>
      <th scope="col"><%= t "ID" , default: "ID"%></th>
      <th scope="col"><%= t "Name" , default: "Name"%></th>
      <th scope="col"><%= t "Email", default: "Email"%></th>
      <th scope="col"><%= t "Job", default: "Job"%></th>
      <th scope="col"><%= t "Salary" , default: "Salary"%></th>
      <th scope="col"><%= t "Employment_status", default: "Employment_status"%> </th>
      <th scope="col"><%= t "Team", default: "Team"%></th>
      <th scope="col"><%= t "Division", default: "Division"%></th>
      <th scope="col" ><%= t "Action" , default: "Action"%> </th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.id %></td>
        <td><%= employee.name %></td>
        <td ><%= employee.email %></td>
        <td><%= employee.job %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.employee_status %></td>
        <td>
          <% if Team.find_by(id: employee.team_id) == nil %>
            None 
          <%else%>
              <%= Team.find_by(id: employee.team_id).name %> 
          <%end%>
        </td>
        <td>
         <% if Division.find_by(id: employee.division_id) == nil %>
            None 
          <%else%>
              <%= Division.find_by(id: employee.division_id).name %> 
          <%end%>
        </td>
        
        <td><button class =  "btn btn-dark"><%= link_to t("Edit"), edit_employee_path(employee) %></button> </td>
        <td> <%= button_to t("Delete"), employee, method: :delete, class: "btn btn-danger"%></td>     
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/employees/new.html.erb
<h1><%= t "New employee"%></h1>

<%= render "form", employee: @employee   %>

<br>

<div>
  <%= link_to t("Back To Employees"), employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to t("Back To Employees"), employees_path,  style: "color:black" %>
</div>