config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    resources :users
    resources :divisions
    resources :targets
    resources :teams
    resources :employees
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    scope "(:locale)", locale: /en|ar/ do
      root :to => "users#index"
    end
  

end

app/models/target.rb
class Target < ApplicationRecord
    belongs_to :team, optional: true
    
     # validation
    validates :title, presence: true, length: {minimum: 3}
    validates :description, length: {minimum: 5}
    validates :start_date, presence: true , comparison: {less_than: :finish_date }
    validates :finish_date, presence: true
    validates :status, presence: true
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: %i[ show edit update destroy ]

  # GET /targets or /targets.json
  def index
    @targets = Target.all
    
  end

  # GET /targets/1 or /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets or /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to target_url(@target), notice: t("create") }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1 or /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to "/targets", notice: t("update")}
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1 or /targets/1.json
  def destroy
    @target.destroy

    respond_to do |format|
      format.html { redirect_to targets_url, notice: t('destroy')  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def target_params
      params.require(:target).permit(:title, :description, :start_date, :finish_date, :status, :team_id)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_with(model: target) do |form| %>
  <% if target.errors.any? %>
    <div style="color: red">
    <h2> <%= t 'globals.forms.messages.errors.multiple errors', count: target.errors.count %> </h2>

      <ul>
        <% target.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "mb-1">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class = "mb-1">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class = "mb-1">
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class = "mb-1">
    <%= form.label :finish_date, style: "display: block" %>
    <%= form.date_field :finish_date, class: "form-control"%>
  </div>

  <div class = "mb-1">
    <%= form.label :team_id, style: "display: block" %>
    <%= form.collection_select :team_id, Team.all, :id, :name, include_blank: true %>
  </div>

  <div class = "mb-1">
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status, class: "form-control"%>
  </div>

  <div class = "mb-1">
    <%= form.submit t("Create Target"), class: "btn btn-primary"%>
  </div>
<% end %>

app/views/targets/_target.html.erb
<div id="<%= dom_id target %>">
  <p>
    <strong><%= t "Title"%>:</strong>
    <%= target.title %>
  </p>

  <p>
    <strong><%= t "Description"%>:</strong>
    <%= target.description %>
  </p>

  <p>
    <strong><%= t "Start date"%>:</strong>
    <%= target.start_date %>
  </p>

  <p>
    <strong><%= t "Finish date"%>:</strong>
    <%= target.finish_date %>
  </p>

  <p>
    <strong><%= t "Status"%>:</strong>
    <%= target.status %>
  </p>

</div>

app/views/targets/edit.html.erb
<h1><%= t "Editing"%></h1>

<%= render "form", target: @target %>

<br>

<div>
  <%= link_to t("Back to targets"), targets_path %>
</div>

app/views/targets/index.html.erb
<h2><%=t "Targets"%></h2>
<%= link_to t("New target"), new_target_path, style: "color: black;" %>

<div id="targets">
  <table class="table ">
  <thead>
    <tr>
      <th scope="col"><%= t "Name"%></th>
      <th scope="col"><%= t "Description"%></th>
      <th scope="col"><%= t "Start Date"%></th>
      <th scope="col"><%= t "Finish Date"%></th>
      <th scope="col"><%= t "Team"%></th>
      <th scope="col"><%= t "Status"%></th>
      <th scope="col"><%= t "Action"%></th>
    </tr>
  </thead>
  <tbody>
    <% @targets.each do |target| %>
      <tr>
        <td><%= target.title %></td>
        <td><%= target.description %></td>
        <td><%= target.start_date %></td>
        <td><%= target.finish_date %></td>
        <td>  <% if Team.find_by(id: target.team_id) == nil %>
            None 
          <%else%>
              <%= Team.find_by(id: target.team_id).name %> 
          <%end%></td>
        <td><%= target.status %></td>
        <td><button class =  "btn btn-dark"><%= link_to t("Edit"), edit_target_path(target) %> </td>
        <td></button> <%= button_to t("Delete"), target, method: :delete, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/targets/new.html.erb
<h1><%= t "New target"%></h1>

<%= render "form", target: @target %>

<br>

<div>
  <%= link_to t("Back to targets"), targets_path %>
</div>

app/views/targets/show.html.erb
<p style="color: green"><%= t notice %></p>

<%= render @target %>

<div>
   <%= link_to t("Back to targets"), targets_path,  style: "color:black" %>

</div>