config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    resources :users
    resources :divisions
    resources :targets
    resources :teams
    resources :employees
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    scope "(:locale)", locale: /en|ar/ do
      root :to => "users#index"
    end
  

end

app/models/division.rb
class Division < ApplicationRecord
    belongs_to :employee, optional: true
    has_many :teams, dependent: :destroy

     # validation
    validates :name, length: {minimum: 2}
    validates :description, length: {minimum: 5}
    validates :manager, length:{minimum: 3} 
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: %i[ show edit update destroy ]

  # GET /divisions or /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1 or /divisions/1.json
  def show
  end
  

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions or /divisions.json
  def create
    @division = Division.new(division_params)
    
    respond_to do |format|
      if @division.save
        format.html { redirect_to division_url(@division), notice: t("create") }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to "/divisions", notice: t("update") }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    @division.destroy

    # when the division destroyed, the team will be destroyed 
    team = Team.find_by(id: @division.team)
    team.destroy
    
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: t("destroy") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def division_params
      params.require(:division).permit(:name, :description, :manager, :team)
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_division.html.erb
<div id="<%= dom_id division %>">
  <p>
    <strong><%= t "Name"%>:</strong>
    <%= division.name %>
  </p>

  <p>
    <strong><%= t "Description"%>:</strong>
    <%= division.description %>
  </p>


  <p>
    <strong><%= t "Manager"%>:</strong>
    <%= division.manager %>
  </p>

</div>

app/views/divisions/_form.html.erb
<%= form_with(model: division) do |form| %>
  <% if division.errors.any? %>
    <div style="color: red">
          <h2> <%= t 'globals.forms.messages.errors.multiple errors', count: division.errors.count %> </h2>


      <ul>
        <% division.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "mb-1">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div class = "mb-1">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

   <div class = "mb-1">
   
    <%= form.label :team, style: "display: block" %>
    <%= form.collection_select :team, Team.all, :id, :name, include_blank: true %>

  </div>

  <div class = "mb-1">
     <% all_emp = Employee.all.map { |e| [e.name] } %>
    <%= form.label :manager, style: "display: block" %>
    <%= form.select(:manager, options_for_select(all_emp), include_blank: true) %>
  </div>

  <div class = "mb-1">
    <%= form.submit t("Create division"), class: "btn btn-primary"%>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1><%= t "Editing"%></h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to t("Back to divisions"), divisions_path %>
</div>

app/views/divisions/index.html.erb
<h2><%= t "Divisions"%></h2>
<%= link_to t("New division"), new_division_path, style: "color: black;" %>

<div id="divisions">
 
<table class="table">
  <thead>
    <tr>
    
      <th scope="col"><%= t "ID"%></th>
      <th scope="col"><%= t "Name"%></th>
      <th scope="col"><%= t "Team"%></th>
      <th scope="col"><%= t "Manager"%></th>
      <th scope="col"><%= t "Description"%></th>
      <th scope="col"><%= t "Action"%></th>

    </tr>
  </thead>
  <tbody>
    <% @divisions.each do |division| %>
      <tr>
      
        <td><%= division.id %></td>
        <td><%= division.name %></td>
        <td>
        <% if Team.find_by(id: division.team) == nil %>
            None 
          <%else%>
              <%= Team.find_by(id: division.team).name %> 
          <%end%>
        <%=  %>
        </td>
        <td><%= division.manager %></td>
        <td><%= division.description %></td>
 
        <td><button class =  "btn btn-dark"><%= link_to "Edit", edit_division_path(division) %></button> </td>
        <td> <%= button_to "Delete", division, method: :delete, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/divisions/new.html.erb
<h1><%= t "New division"%></h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to t("Back to divisions"), divisions_path %>
</div>

app/views/divisions/show.html.erb
<p style="color: green"><%= t notice %></p>

<%= render @division %>

<div>
  <%= link_to t("Back to divisions"), divisions_path,  style: "color:black" %>

</div>